### ISSUE TITLE
Неправильная конфигурация тестирования в Google Play

### ISSUE THREAD

**Issue by Luonic** [mosmetro-android/module-captcha-recognition#3]
App not available for this account

Your account isn't currently eligible for this app's testing program.
If you've been invited to become a tester, make sure you're signed in to the account that was invited to the testing program. If you've been invited to a Google Group or Google+ Community as part of the program, make sure you've joined the Group or Community.

**Comment by urandon** [comment]
Подтверждаю

**Comment by TheDrHax** [comment]
Я при создании проекта тестирование не включил. Теперь всё [работает](https://play.google.com/apps/testing/pw.thedrhax.captcharecognition).
